var dojoConfig = {
    baseUrl: '.',
    packages: [{
        name: 'dgrid',
        location: 'bower_components/dgrid',
    }, {
        name: 'dijit',
        location: 'bower_components/dijit',
    }, {
        name: 'dojo',
        location: 'bower_components/dojo',
    }, {
        name: 'dojox',
        location: 'bower_components/dojox',
    }, {
        name: 'dstore',
        location: 'bower_components/dstore',
    }, {
        name: 'esri',
        location: 'bower_components/esri',
    }, {
        name: 'moment',
        location: 'bower_components/moment',
    }, {
        name: 'react',
        location: 'bower_components/react/dist',
        main: 'react'
    }, {
        name: 'react-dom',
        location: 'bower_components/react-dom/dist',
        main: 'react-dom'
    }, {
        name: 'react-router',
        location: 'bower_components/react-router/umd',
        main: 'ReactRouter'
    }, {
      name: 'react-bootstrap',
      location: 'bower_components/react-bootstrap/dist',
      main: 'react-bootstrap'
    }, {
      name: 'xstyle',
      location: 'bower_components/xstyle'
    }, {
      name: 'put-selector',
      location: 'bower_components/put-selector',
      main: 'put'
    }],
  deps: ['xstyle/main']
};